### ISSUE TITLE
No sketch.sh

### ISSUE THREAD

**Issue by nehalmamgain** [User1m/sketch2pix#1]
@User1m Hi, could you please point to where sketch.sh is or what should be in this script?

**Comment by user1m** [comment]
Hi @nehalmamgain,

The repo has changed quite a bit as we're now using a custom DNN vs Pix2Pix.

But to answer your question. Yes `sketch.sh` is gone. Please use instead:

```
> python sketch2pix/dataset/PencilSketch/gen_sketch_and_gen_resized_face.py \
/path/to/image_folder /path/to/face_folder /path/to/sketch_folder
```
That python script will output an "sketchified" image to the `/path/to/sketch_folder`.
Please refer to the python code for how it operates.

Thanks
